### ISSUE TITLE
Implement Local llm 

### ISSUE THREAD

**Issue by Jhonatan89lutt** [ranjeetds/super-scraper#1]
Is it possible to implement local llms , lm studio serving the llms for me to use with this?

**Comment by ranjeetds** [comment]
Yes. It's very easy to update backend script and add support local llm's like llama or Mixtral. You need to update backend `main.py` file `generate_scraper` method with appropriate imports. 

Do let me know if this helps or you need help with it.

**Comment by Jhonatan89lutt** [comment]
Hi Sir I really not that good with this myself :( I trying to learn , I have llm studio and maybe to integrate it as server to your scraper. 
I have a great api service BIG-AGI connections with the admin maybe to integrate your service to that one ?

**Comment by ranjeetds** [comment]
Can you share your llm studio details? This repo will need substantial improvements to be integrated into production.

**Comment by Jhonatan89lutt** [comment]
I think i typed wrong, its https://lmstudio.ai
And using that to serve my llm's Locally.
Then I use BIG-Agi as my main work space https://big-agi.com 
The owner of Big-Agi is also interested in getting this to work to implement a sort of webscrape function 🤗 
So for me it's just the scrape function where it would be great to use your project to use served llm to pick up data to combine with the scrape prowess to make it better. Like they do with firecrawl project but I don't think they use local llm

**Comment by ranjeetds** [comment]
This is great thought process. Let me know if I can contribute to your project with local llm and big-agi. We can do great customizations to the scraper to accommodate generic flows. Let me know how we can connect further (Discord?)

**Comment by Jhonatan89lutt** [comment]
Try find me at SmileKula#5146 or Jhonatan89

I will direct you to the main geek that is admin as soon as you are in there

**Comment by ranjeetds** [comment]
Have sent request from kingextabs. Do accept. Closing the thread for now

**Comment by Jhonatan89lutt** [comment]
It looks like i didnt Get it, try jhonatankyllo
